### ISSUE TITLE
Реализовать парсинг ImportPython

### ISSUE THREAD

**Issue by WarmongeR1** [pythondigest/pythondigest#87]
Пример выпуска: http://importpython.com/blog/post/importpython-issue-67
RSS с ссылками на выпуски: http://importpython.com/blog/feed/

**Comment by MrLokans** [comment]
Какие действия необходимо предварительно сделать, чтобы стало возможным использовать команды импорта? 
После обычного python manage.py migrate и запуска, например, python manage.py import_python_weekly "url" кидается эксепшн
```
digest.models.DoesNotExist: Resource matching query does not exist.
```

Я сейчас работаю над парсерами importpython и Pycoders Weekly, но мне непонятно, что необходимо сделать, чтобы увидеть результат работы, спасибо.

**Comment by WarmongeR1** [comment]
Сделал коммит, который сам создает нужный Resource объект (https://github.com/pythondigest/pythondigest/commit/7105b489ea7f6e5712f4c3afb51a0a71b06bb4bb)

Когда запускаешь команду, он парсит страницу, создает набор объектов Item. Они со статусом "autoimport" и они НЕ отображаются нигде кроме админки. 
Чтобы увидеть какие спарсились надо зайти в админку по ссылке `/admin/digest/item/`.

**Comment by MrLokans** [comment]
Можешь черкануть где-нибудь в README минимальный набор шагов, который нужен для того, чтобы поднять рабоющий сайт на своей машине с нуля? Я могу потом создать Vagrant-машину, с кукбуком для локального развертывания или Docker-образ.

Необходима какая-то дополнительная подготовка для того, чтобы работать с моделью Section:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/venvs/digest/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/user/venvs/digest/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/venvs/digest/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/venvs/digest/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/user/Dropbox/Projects/Python/pythondigest/digest/management/commands/import_importpython.py", line 147, in handle
    main(number=options['number'])
  File "/home/user/Dropbox/Projects/Python/pythondigest/digest/management/commands/import_importpython.py", line 129, in main
    print(list(with_rules_applied))
  File "/home/user/Dropbox/Projects/Python/pythondigest/digest/management/commands/import_importpython.py", line 110, in _apply_rules
    item.update(apply_video_rules(item))
  File "/home/user/Dropbox/Projects/Python/pythondigest/digest/management/commands/__init__.py", line 310, in apply_video_rules
    if item_data.get('section') == Section.objects.get(title='Видео') \
  File "/home/user/venvs/digest/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/user/venvs/digest/lib/python3.5/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
digest.models.DoesNotExist: Section matching query does not exist.
```

**Comment by WarmongeR1** [comment]
Да, черкану, как время появится.

А section, есть в `digest/fixtures/sections.yaml`, который надо загрузить

`python manage.py loaddata digest/fixtures/sections.yaml`

**Comment by MrLokans** [comment]
@WarmongeR1 при попытке зайти на разные URL-ы (например '/admin/digest/item/' или просто главная страница) крашится с эксепшеном
```
  File "/home/user/venvs/digest/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: secretballot_vote
```
Зависимости установлены и python manage migrate предварительно сделан

**Comment by WarmongeR1** [comment]
Давай паузу в пару дней сделаем. 
Я сяду, сделаю README для разработчиков, а ты по нему сможешь смело сделать Vagrant конфиг.

**Comment by MrLokans** [comment]
Да, давай, пока feature-бранчи позавожу.

**Comment by WarmongeR1** [comment]
Вот здесь - https://github.com/pythondigest/pydigest-dataset/tree/master/src  есть парсеры в виде мусорном виде. Но можно заиспользовать какие-то куски
